FROM php:7.4-apache
RUN apt-get update -y && apt-get install -y libpng-dev \
    && docker-php-ext-install gd

RUN docker-php-ext-install pdo \
    pdo_mysql

# Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Clean repository
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set /html to /html/web
ENV APACHE_DOCUMENT_ROOT=/var/www/html/web
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf